#!/bin/bash
#
#BSUB -q 52-large
#BSUB -W 24:00
#BSUB -J 0.37
#BSUB -o cp2k.%J.stdout
#BSUB -e cp2k.%J.stderr
#BSUB -n 140
#BSUB -R "span[ptile=28]"

# add modulefiles
module load intel/17.5.239 mpi/intel/2017.5.239
module load gcc/5.5.0
module load cp2k/7.1

for i in $(seq 0 1 159)
do
    #mpiexec.hydra cp2k.popt refer_110_${i}.inp >& refer_110__${i}
    mpiexec.hydra cp2k.popt train_${i}.inp >& output__${i}
    rm *bak*
    sleep 30s 
done
